name:                fpopt
version:             0.1.0.0
github:              "github.com/sampollard/fpopt"
license:             GPLv3
author:              "Samuel D. Pollard"
maintainer:          "sam.d.pollard@gmail.com"
copyright:           "2021 Samuel D. Pollard"

# extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sampollard/reduce-error#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  fpopt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpopt

tests:
  fpopt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpopt
