#!/bin/sh
if [ "$#" -ne 1 ]; then
	echo "usage: ./nekpmpi <number of processors>
	exit 1
fi
smpirun -hostfile ../../../../topologies/hostfile-fattree-16.txt \
	-platform ../../../../topologies/fattree-16.xml \
	--cfg=smpi/host-speed:90000000000f \
	-np $2 ./nekbone 1 > "log-fattree-16-$2.txt"
